// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

[Table("Access")]
public partial class Access
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string ManuName { get; set; }

    [StringLength(50)]
    public string Controller { get; set; }

    [StringLength(50)]
    public string Action { get; set; }

    [ForeignKey("AccessId")]
    [InverseProperty("Accesses")]
    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}