// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

[Table("AdditionalClockIn")]
public partial class AdditionalClockIn
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("EmployeesID")]
    public int EmployeesId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime AdditionalTime { get; set; }

    public int Status { get; set; }

    [StringLength(500)]
    public string Reason { get; set; }

    [Column("ApprovalEmployeeID")]
    public int ApprovalEmployeeId { get; set; }

    [ForeignKey("EmployeesId")]
    [InverseProperty("AdditionalClockIns")]
    public virtual Employee Employees { get; set; }
}