// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

[Table("Approval")]
public partial class Approval
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    public int TableType { get; set; }

    [Column("TableID")]
    public int TableId { get; set; }

    public bool? Status { get; set; }

    [StringLength(50)]
    public string Remark { get; set; }
}