// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Repository.Enums;

namespace Repository.Models;

[Table("Clock")]
public partial class Clock
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("EmployeesID")]
    public int EmployeesId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    public ClockStatusEnum Status { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal Latitude { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal Longitude { get; set; }

    [ForeignKey("EmployeesId")]
    [InverseProperty("Clocks")]
    public virtual Employee Employees { get; set; }
}