// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

[Table("CompLeave")]
public partial class CompLeave
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("OvertimeID")]
    public int OvertimeId { get; set; }

    public int CompMin { get; set; }

    [ForeignKey("OvertimeId")]
    [InverseProperty("CompLeaves")]
    public virtual OvertimeApplication Overtime { get; set; }
}