// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

[Table("Flextime")]
public partial class Flextime
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    public int FlexibleTime { get; set; }

    [Required]
    public bool? MoveUp { get; set; }
}