// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

[Table("OvertimeApplication")]
public partial class OvertimeApplication
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("EmployeesID")]
    public int EmployeesId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EndTime { get; set; }

    [Required]
    [StringLength(50)]
    public string Reason { get; set; }

    public bool Status { get; set; }

    [Column("ApprovalEmployeeID")]
    public int ApprovalEmployeeId { get; set; }

    [InverseProperty("Overtime")]
    public virtual ICollection<CompLeave> CompLeaves { get; set; } = new List<CompLeave>();

    [ForeignKey("EmployeesId")]
    [InverseProperty("OvertimeApplications")]
    public virtual Employee Employees { get; set; }
}