// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Repository.Enums;

namespace Repository.Models;

[Table("RequestStatus")]
public partial class RequestStatus
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    public TableTypeEnum TableType { get; set; }

    [Column("TableID")]
    public int TableId { get; set; }

    public int Status { get; set; }
}