// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

[Table("Shift")]
public partial class Shift
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ShiftsDate { get; set; }

    [Column("EmployeesID")]
    public int EmployeesId { get; set; }

    [Column("ShiftScheduleID")]
    public int ShiftScheduleId { get; set; }

    [ForeignKey("EmployeesId")]
    [InverseProperty("Shifts")]
    public virtual Employee Employees { get; set; }

    [ForeignKey("ShiftScheduleId")]
    [InverseProperty("Shifts")]
    public virtual ShiftSchedule ShiftSchedule { get; set; }
}