// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

[Table("User")]
public partial class User
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Account { get; set; }

    [Required]
    public string Password { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PasswordDate { get; set; }

    public bool Stop { get; set; }

    [Required]
    public string Salt { get; set; }

    public int RoleId { get; set; }

    [ForeignKey("Id")]
    [InverseProperty("User")]
    public virtual UserOfAdmin UserOfAdmin { get; set; }

    [ForeignKey("Id")]
    [InverseProperty("User")]
    public virtual Employee IdNavigation { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("Users")]
    public virtual Role Role { get; set; }
}