// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

[Table("UserOfAdmin")]
public partial class UserOfAdmin
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    [ForeignKey("Id")]
    public virtual User User { get; set; }
}